# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'reactNativeBoilerPlateV2RN55' do
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end